# .travis.yml file
cache: apt
language: python
python: 
    - "2.7"
    - "3.6"
    - "3.7"
    

install:
    - conda env create --file environment.yml
    - source activate test-environment 
    - python setup.py install
    - pip install -r requirements.txt

script:
    - py.test test --cov=wRadia

after_script:
    - coveralls